  init_scale: 0.1
  learning_rate: 2.0
  max_grad_norm: 5
  num_layers: 2
  unroll_length: 20
  embedding_dim: 200
  max_epoch: 4
  max_max_epoch: 13
  keep_prob: 1.0
  lr_decay: 0.5
  batch_size: 20
  vocab_size: 10003
