# Model params
embedding_dim: 800
batch_size: 20
unroll_length: 35
num_layers: 2

# Optimization params
max_grad_norm: 5
l2_reg: 0.001
opt_method: "RMSPropOptimizer"
opt_params:
  learning_rate: 0.01
